### ISSUE TITLE
how did you get forever combo?

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [SanicBTW/FNF-PsychEngine-0.3.2h#10]

**Comment by MemeHoovy** [comment]
Hey Levi, I’m gonna be back home Wednesday (but don’t count on it), and it’s a very long drive back home, so I might not be able to answer you for a while

**Comment by LEVIXDDLMAO** [comment]
its all good, i havent been doing anything lol

**Comment by MemeHoovy** [comment]
yeah, I haven’t really been able to do anything either lol

**Comment by LEVIXDDLMAO** [comment]
lol im working on the html5 mod state

**Comment by MemeHoovy** [comment]
neato, it’s hard to get mods working on html5 tbh, and Lua is just basically impossible

**Comment by LEVIXDDLMAO** [comment]
i gotta rewirte the mod menu state and figure something out with lua and other crap

**Comment by MemeHoovy** [comment]
Cool, going to sleep gn

**Comment by LEVIXDDLMAO** [comment]
gn

**Comment by SanicBTW** [comment]
wtf im not getting notifications at all

**Comment by SanicBTW** [comment]
> neato, it’s hard to get mods working on html5 tbh, and Lua is just basically impossible

have you tested hxvm-luajit? https://github.com/nebulazorua/hxvm-luajit i was trying to test it out but i cant get yarn to build dunno how lol, try that out when you have most of the html5 mod support working, if you get it, mind if i borrow some code about it?

**Comment by SanicBTW** [comment]
also for levi how did you even notice that i coded in the forever combo are you watchin the private development 😭

**Comment by SanicBTW** [comment]
anyways so i figured it out and it was really easy, just go to your PlayState.hx then go to popUpScore, and just instead of having (or something similar) 
```
if (combo >= 1000)
	seperatedScore.push(Math.floor(combo / 1000) % 10);

seperatedScore.push(Math.floor(combo / 100) % 10);
seperatedScore.push(Math.floor(combo / 10) % 10);
seperatedScore.push(combo % 10);
```
make it this instead
```
if (combo >= 1000)
	seperatedScore.push(Math.floor(combo / 1000) % 10);

if (combo >= 100)
	seperatedScore.push(Math.floor(combo / 100) % 10);

if (combo >= 10)
	seperatedScore.push(Math.floor(combo / 10) % 10);

seperatedScore.push(combo % 10);
```
if you need me to actually code it in your thing tell me which folder/repo in your user folder

**Comment by SanicBTW** [comment]
dw, you can try anytime as long as you get some stuff working and can contribute to it sometime thats fine

**Comment by SanicBTW** [comment]
take ur time

**Comment by MemeHoovy** [comment]
I will when I get back home

**Comment by SanicBTW** [comment]
sure

**Comment by LEVIXDDLMAO** [comment]
> also for levi how did you even notice that i coded in the forever combo are you watchin the private development 😭

i was playing private devlopemnt, lol because i tought it was off and then i got bored

**Comment by SanicBTW** [comment]
Bro GitHub mobile ain't notifying shit

**Comment by LEVIXDDLMAO** [comment]
xd

**Comment by MemeHoovy** [comment]
hey, I'm back home

**Comment by SanicBTW** [comment]
That's great

**Comment by LEVIXDDLMAO** [comment]
i got a new laptop, and i added forever combo :D

**Comment by LEVIXDDLMAO** [comment]
and thats great memehoovy! i just got the notif from sanco

**Comment by MemeHoovy** [comment]
yeah, I might try writing an original song that's not FNF

**Comment by LEVIXDDLMAO** [comment]
ooo

**Comment by LEVIXDDLMAO** [comment]
im playing one chance ( not the fnf mod )

**Comment by MemeHoovy** [comment]
sweet

**Comment by LEVIXDDLMAO** [comment]
aw the wife just died D:

**Comment by LEVIXDDLMAO** [comment]
D: its sad now

**Comment by MemeHoovy** [comment]
yeah, it gets sad, I've seen the entire game but I'm not gonna spoil anything

**Comment by SanicBTW** [comment]
> i got a new laptop, and i added forever combo :D

Yoooo that's sick

**Comment by SanicBTW** [comment]
Anyways I'm going to sleep gn guys

**Comment by LEVIXDDLMAO** [comment]
gn! i jumped at the end

**Comment by MemeHoovy** [comment]
> > neato, it’s hard to get mods working on html5 tbh, and Lua is just basically impossible
> 
> have you tested hxvm-luajit? https://github.com/nebulazorua/hxvm-luajit i was trying to test it out but i cant get yarn to build dunno how lol, try that out when you have most of the html5 mod support working, if you get it, mind if i borrow some code about it?

look at kade engine source code, it uses that

**Comment by MemeHoovy** [comment]
also Imma go to bed, it's pretty late for me

**Comment by SanicBTW** [comment]
> > > neato, it’s hard to get mods working on html5 tbh, and Lua is just basically impossible
> > 
> > have you tested hxvm-luajit? https://github.com/nebulazorua/hxvm-luajit i was trying to test it out but i cant get yarn to build dunno how lol, try that out when you have most of the html5 mod support working, if you get it, mind if i borrow some code about it?
> 
> as for that, look at kade engine source code, it uses that

Alrighty, will do

**Comment by SanicBTW** [comment]
> also Imma go to bed, it's pretty late for me

Gnn
