### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by MemeHoovy** [SanicBTW/FNF-PsychEngine-0.3.2h#17]
Try putting the bugs & issues in the readme or a text file, instead of just using the issue tracker, I'd feel it would be better to do that instead.

**Comment by SanicBTW** [comment]
I totally agree with you, thanks for the suggestion! I was only using the GitHub issue tracker because I thought I could take advantage of some features but as I don't really know how to I'm just wasting it so I'll totally move to a different place

**Comment by MemeHoovy** [comment]
OK great, glad I could help. 👍🏻
