### ISSUE TITLE
what is this

### ISSUE THREAD

**Issue by fnfporterhi** [SanicBTW/FNF-PsychEngine-0.3.2h#19]
is it supposed to add score when botplay is on?

**Comment by fnfporterhi** [comment]
sorry to make a new issue. ill close it when we have a solution. this isnt a discussion. just need a answer

**Comment by SanicBTW** [comment]
The score, accuracy and misses aren't saved when using botplay

**Comment by fnfporterhi** [comment]
it kinda was showing it. i didnt use it the full song. hold on and ill screenshot an example.

**Comment by fnfporterhi** [comment]
![Screenshot 2022-12-12 9 48 03 AM](https://user-images.githubusercontent.com/99343223/207075447-eb787513-28d7-4bb0-af24-c8b43ea1a2d8.png)
like this

**Comment by fnfporterhi** [comment]
also i kinda cant really access the online songs list

**Comment by SanicBTW** [comment]
when i say its not saved it means that neither on freeplay nor in story menu the score or accuracy is displayed (its not saved on the flixel save)

**Comment by SanicBTW** [comment]
> also i kinda cant really access the online songs list

i forgot to update the file, power died some days ago, will update now

**Comment by SanicBTW** [comment]
done

**Comment by SanicBTW** [comment]
> when i say its not saved it means that neither on freeplay nor in story menu the score or accuracy is displayed (its not saved on the flixel save)

to add more meaning to this:

basically i made it that when finishing the song it doesnt save scores on the save data and simply skips this process and changes the song, this doesnt mean that when playing without botplay scores and stuff arent saved, they are but they aren't when using botplay or practice mode, it displays the bot score and so it wont be saved

**Comment by SanicBTW** [comment]
idk if you get it but if you finished playin a song with botplay on you would notice that nothing is saved

**Comment by fnfporterhi** [comment]
> > when i say its not saved it means that neither on freeplay nor in story menu the score or accuracy is displayed (its not saved on the flixel save)
> 
> to add more meaning to this:
> 
> basically i made it that when finishing the song it doesnt save scores on the save data and simply skips this process and changes the song, this doesnt mean that when playing without botplay scores and stuff arent saved, they are but they aren't when using botplay or practice mode, it displays the bot score and so it wont be saved

i just noticed thanks sanco :)

**Comment by fnfporterhi** [comment]
also will there ever be multi-key support for this engine?

**Comment by SanicBTW** [comment]
i thought on adding it but it takes a bunch of work and shit sooo maybe in another update, im currently workin on mod support with forever engine modules n shit

**Comment by SanicBTW** [comment]
maybe if you can give me some assets for multi keys (not from shaggy) maybe i can work on it

**Comment by fnfporterhi** [comment]
i literally fucking forgot to live lmao


i’ll post some multikey psych engine assets to a repo and tag you in it

**Comment by SanicBTW** [comment]
sure, thanks!
