### ISSUE TITLE
bruh my school blocked the tk things 😭

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [SanicBTW/FNF-PsychEngine-0.3.2h#20]
now i cant use it unless you change it back to sancopublic.ddns. 😭

**Comment by MemeHoovy** [comment]
hello

**Comment by SanicBTW** [comment]
> now i cant use it unless you change it back to sancopublic.ddns. 😭

Aw hell nah

**Comment by SanicBTW** [comment]
Gotta map the ports to the router again give me some time cuz I'm sick too

**Comment by SanicBTW** [comment]
Also why did you remove the star from the repo 😭

**Comment by SanicBTW** [comment]
ayo levi sorry for being gone for some days, my sickness was actually killing me, today i got some strength to get on the chromebook and finally turn on some stuff and fix the domain (sancopublic.ddns is available again to use) have fun!

**Comment by LEVIXDDLMAO** [comment]
all good, and dope!
