### ISSUE TITLE
my discord broke lmao

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [SanicBTW/FNF-PsychEngine-0.3.2h#21]

**Comment by SanicBTW** [comment]
LMFAO WHAT

**Comment by SanicBTW** [comment]
press ctrl +r

**Comment by LEVIXDDLMAO** [comment]
xd

**Comment by LEVIXDDLMAO** [comment]
I did its still broken

**Comment by SanicBTW** [comment]
reopen it

**Comment by LEVIXDDLMAO** [comment]
:0

**Comment by LEVIXDDLMAO** [comment]
Still like bruh T^T

**Comment by SanicBTW** [comment]
what happened:Skull:

**Comment by LEVIXDDLMAO** [comment]
idk im using an unblocker

**Comment by LEVIXDDLMAO** [comment]
discord is blocked for me

**Comment by SanicBTW** [comment]
maybe it cant reach the discord api

**Comment by LEVIXDDLMAO** [comment]
maybe

**Comment by MemeHoovy** [comment]
sad

**Comment by LEVIXDDLMAO** [comment]
huh

**Comment by MemeHoovy** [comment]
hi, also you got pro, nice :)

**Comment by LEVIXDDLMAO** [comment]
i canceled it lmao

**Comment by LEVIXDDLMAO** [comment]
imma rebuy it

**Comment by LEVIXDDLMAO** [comment]
there we go

**Comment by MemeHoovy** [comment]
oh, alright lol

**Comment by LEVIXDDLMAO** [comment]
:D

**Comment by LEVIXDDLMAO** [comment]
166

**Comment by SanicBTW** [comment]
waht

**Comment by LEVIXDDLMAO** [comment]
166 bucks :D

**Comment by SanicBTW** [comment]
holy

**Comment by LEVIXDDLMAO** [comment]
:D

**Comment by SanicBTW** [comment]
give me some

**Comment by LEVIXDDLMAO** [comment]
huh?

**Comment by LEVIXDDLMAO** [comment]
you want me to fix my phone or?

**Comment by SanicBTW** [comment]
fix it lmao

**Comment by LEVIXDDLMAO** [comment]
lol

**Comment by LEVIXDDLMAO** [comment]
but im gonna fix my phone

**Comment by LEVIXDDLMAO** [comment]
how do i make note splashes not lagg?

**Comment by LEVIXDDLMAO** [comment]
@SanicBTW

**Comment by SanicBTW** [comment]
idk

**Comment by LEVIXDDLMAO** [comment]
crap

**Comment by MemeHoovy** [comment]
Hey Levi, I asked my mom if I could get pro, since it's 4$ a month

**Comment by MemeHoovy** [comment]
since it's cheaper then nitro on discord

**Comment by SanicBTW** [comment]
i use the forever method which instead of recycling the notesplash object it just makes it invisible after finishing the anim

**Comment by LEVIXDDLMAO** [comment]
lol dope

**Comment by MemeHoovy** [comment]
she's at work rn though

**Comment by MemeHoovy** [comment]
and idk if she changed her number

**Comment by LEVIXDDLMAO** [comment]
> i use the forever method which instead of recycling the notesplash object it just makes it invisible after finishing the anim

can you do that for infinity engine ( I like having notesplahes but they lag my game

**Comment by LEVIXDDLMAO** [comment]
> and idk if she changed her number

hm?

**Comment by MemeHoovy** [comment]
> > and idk if she changed her number
> 
> hm?

nothing, we're gonna open presets tomorrow

**Comment by LEVIXDDLMAO** [comment]
ooo i opened mine today :D

**Comment by SanicBTW** [comment]
> > i use the forever method which instead of recycling the notesplash object it just makes it invisible after finishing the anim
> 
> can you do that for infinity engine ( I like having notesplahes but they lag my game

im literally sufferin from headache and week read directory asset shit and it kinda takes time give me some min before i add it to your engien

**Comment by LEVIXDDLMAO** [comment]
ok :D

**Comment by SanicBTW** [comment]
FINALLY I GOT IT TO WORKKKKKKKK

**Comment by SanicBTW** [comment]
```haxe
	// me when spend half an hour trying to fix path issue while library :troll:
	private static function reloadFromAssets(isStoryMode:Null<Bool> = false)
	{
		// smartass code
		var library = Assets.getLibrary("weeks");
		for(asset in library.list(null))
		{
			if (!asset.endsWith(".json"))
				return;

			var weekName = asset.replace("assets/weeks/", "").replace(".json", "");
			if (weeksLoaded.exists(weekName))
				return;

			// shit wasnt workin alone with assets/weeks/week.json, it needed the library path too :skull:
			var weekPath = Paths.getLibraryPath('$weekName.json', 'weeks');
			var week:WeekFile = getWeekFile(weekPath);
			if (week == null)
				return;

			var weekFile:WeekData = new WeekData(week, weekName);
			if (weekFile != null
				&& (isStoryMode == null 
					|| (isStoryMode && !weekFile.hideStoryMode) 
					|| (!isStoryMode && !weekFile.hideFreeplay)))
			{
				weeksLoaded.set(weekName, weekFile);
				weeksList.push(weekName);
			}
		}
	}
```

**Comment by SanicBTW** [comment]
fuck weeklist.txt

**Comment by LEVIXDDLMAO** [comment]
lol

**Comment by SanicBTW** [comment]
code is actually really good tf

**Comment by SanicBTW** [comment]
pushed, now gotta fix your note splashes thingy

**Comment by LEVIXDDLMAO** [comment]
okay :D

**Comment by SanicBTW** [comment]
accounts mixing up in codeserver 💀

**Comment by LEVIXDDLMAO** [comment]
huh?

**Comment by SanicBTW** [comment]
i just commited to a repo with your account

**Comment by LEVIXDDLMAO** [comment]
witch one?

**Comment by SanicBTW** [comment]
a psych engine fork i just did lol

**Comment by LEVIXDDLMAO** [comment]
oh lol sorry

**Comment by SanicBTW** [comment]
dw did another branch

**Comment by LEVIXDDLMAO** [comment]
kk

**Comment by LEVIXDDLMAO** [comment]
hows it going

**Comment by SanicBTW** [comment]
does your engine play splashes on dad strums or not

**Comment by LEVIXDDLMAO** [comment]
nope

**Comment by SanicBTW** [comment]
oki

**Comment by SanicBTW** [comment]
im gonna do some hacky stuff

**Comment by LEVIXDDLMAO** [comment]
?

**Comment by LEVIXDDLMAO** [comment]
wdym hacky things

**Comment by SanicBTW** [comment]
im gonna try to do a workaround cuz i had to copy the whole forever strum code to make the note splash work like them, so what im gonna try to do is to add the note splashes to the grp note splashes array and get the array index based on the note data % 4

**Comment by LEVIXDDLMAO** [comment]
okay

**Comment by SanicBTW** [comment]
alright its workin fine, last test

**Comment by LEVIXDDLMAO** [comment]
do you want me to compile or are you doing it?

**Comment by SanicBTW** [comment]
im doin it thats why i said its workin fine lmao

**Comment by LEVIXDDLMAO** [comment]
lol

**Comment by LEVIXDDLMAO** [comment]
I did alot of debug stuff

**Comment by SanicBTW** [comment]
yup its workin perfectly fine, enjoy :D

**Comment by LEVIXDDLMAO** [comment]
:D

**Comment by LEVIXDDLMAO** [comment]
Does it lag?

**Comment by SanicBTW** [comment]
tested it on blammed, runs smoothly

**Comment by LEVIXDDLMAO** [comment]
dope

**Comment by LEVIXDDLMAO** [comment]
I have erect remixes ( diff )

**Comment by LEVIXDDLMAO** [comment]
they could us some bug fixes but

**Comment by LEVIXDDLMAO** [comment]
they work

**Comment by SanicBTW** [comment]
what

**Comment by LEVIXDDLMAO** [comment]
maybe could be hitsounds

**Comment by LEVIXDDLMAO** [comment]
NEB ANSWERED THE PULL THING MEMEHOOVY

**Comment by LEVIXDDLMAO** [comment]
YOOOOOOo

**Comment by MemeHoovy** [comment]
I saw

**Comment by LEVIXDDLMAO** [comment]
LETS GOO

**Comment by LEVIXDDLMAO** [comment]
@sanco

**Comment by SanicBTW** [comment]
me

**Comment by LEVIXDDLMAO** [comment]
Wsp

**Comment by SanicBTW** [comment]
suffering
![image](https://user-images.githubusercontent.com/58010536/209493191-d9113f32-6f63-46d6-ac71-43c2cb3bdf7d.png)

**Comment by SanicBTW** [comment]
workin with 0.6.3 🤡

**Comment by LEVIXDDLMAO** [comment]
:0

**Comment by SanicBTW** [comment]
im tired

**Comment by LEVIXDDLMAO** [comment]
get some sleep

**Comment by SanicBTW** [comment]
i might've done one of my best codes again

**Comment by LEVIXDDLMAO** [comment]
hm?

**Comment by SanicBTW** [comment]
```haxe
var library = Assets.getLibrary("weeks");
		for (asset in library.list(null))
		{
			for (j in 0...directories.length)
			{
				if (asset.endsWith(".json"))
				{
					var weekName = asset.replace('${directories[j]}weeks/', "").replace(".json", "");
					var fileToCheck:String = (directories[j].contains("assets") ? Paths.getLibraryPath('$weekName.json', 'weeks') : '${directories[j]}weeks/$weekName.json');
					if (!weeksLoaded.exists(weekName))
					{
						var week:WeekFile = getWeekFile(fileToCheck);
						if (week != null)
						{
							var weekFile:WeekData = new WeekData(week, weekName);

							#if MODS_ALLOWED
							if(j >= originalLength) {
								weekFile.folder = directories[j].substring(Paths.mods().length, directories[j].length-1);
							}
							#end

							if (weekFile != null
								&& (isStoryMode == null
									|| (isStoryMode && !weekFile.hideStoryMode)
									|| (!isStoryMode && !weekFile.hideFreeplay)))
							{
								weeksLoaded.set(weekName, weekFile);
								weeksList.push(weekName);
							}
						}
					}
				}
			}
		}
```
no weeklist.txt asset support on 0.6.3 with mod support included, further testing with mod support is required

**Comment by LEVIXDDLMAO** [comment]
ooo

**Comment by SanicBTW** [comment]
im cryin rn

**Comment by LEVIXDDLMAO** [comment]
why?

**Comment by MemeHoovy** [comment]
wait what?

**Comment by LEVIXDDLMAO** [comment]
:0

**Comment by SanicBTW** [comment]
im so tired

**Comment by LEVIXDDLMAO** [comment]
:0

**Comment by MemeHoovy** [comment]
go sleep Sanco

**Comment by SanicBTW** [comment]
workin perfectly fine 
![image](https://user-images.githubusercontent.com/58010536/209493895-e91e555b-269c-4e40-9541-eeabc045c2e4.png)

**Comment by LEVIXDDLMAO** [comment]
lmao im doing  a new fps junk lmao

**Comment by LEVIXDDLMAO** [comment]
@MemeHoovy

**Comment by MemeHoovy** [comment]
what?

**Comment by LEVIXDDLMAO** [comment]
Do you know how to add 120 fps to psych? like https://github.com/Stilic/FNF-FlatyEngine Stilic's engine

**Comment by MemeHoovy** [comment]
hmm, let me think

**Comment by MemeHoovy** [comment]
change the framerate thing in main to 120

**Comment by LEVIXDDLMAO** [comment]
I did that

**Comment by LEVIXDDLMAO** [comment]
![image](https://user-images.githubusercontent.com/92174516/209494992-29db1abd-fde3-41c5-8c78-0f3f0aa177f9.png)

**Comment by MemeHoovy** [comment]
well uh, idk, he has his ways

**Comment by LEVIXDDLMAO** [comment]
lmao

**Comment by SanicBTW** [comment]
me when vsync

**Comment by LEVIXDDLMAO** [comment]
> me when vsync

lmao Stilic got 120 on a chromebook

**Comment by SanicBTW** [comment]
yeah im on a chromebook

**Comment by SanicBTW** [comment]
![image](https://user-images.githubusercontent.com/58010536/209495165-508da7b1-5562-4a2a-98a3-dbabd75872b8.png)

**Comment by LEVIXDDLMAO** [comment]
thats what i wanna do

**Comment by LEVIXDDLMAO** [comment]
I know how to add the of health bars :D

**Comment by LEVIXDDLMAO** [comment]
of*

**Comment by SanicBTW** [comment]
fuck the notesplash offset is real good

**Comment by LEVIXDDLMAO** [comment]
hm?

**Comment by SanicBTW** [comment]
![image](https://user-images.githubusercontent.com/58010536/209495278-83ab0236-4933-420b-81bc-16b7d17d09c7.png)
its actually pretty much centered

**Comment by LEVIXDDLMAO** [comment]
lol

**Comment by LEVIXDDLMAO** [comment]
im wonder how he got 120 fps

**Comment by LEVIXDDLMAO** [comment]
hmmm

**Comment by LEVIXDDLMAO** [comment]
are you guys looking for a way?

**Comment by MemeHoovy** [comment]
just turn vsync off idk

**Comment by SanicBTW** [comment]
where

**Comment by LEVIXDDLMAO** [comment]
> just turn vsync off idk

bruh

**Comment by LEVIXDDLMAO** [comment]
> where
 
for fps junk  https://github.com/Stilic/FNF-FlatyEngine

**Comment by SanicBTW** [comment]
what

**Comment by LEVIXDDLMAO** [comment]
I wanna get 120 fps on infinity engine

**Comment by SanicBTW** [comment]
then change framerate to 120

**Comment by LEVIXDDLMAO** [comment]
where in Main.hx

**Comment by SanicBTW** [comment]
ye

**Comment by LEVIXDDLMAO** [comment]
i did 
![Screenshot 2022-12-25 8 10 54 PM](https://user-images.githubusercontent.com/92174516/209496104-1aef2a5a-8b8c-4ac3-99c2-61d1a28960e5.png)

**Comment by SanicBTW** [comment]
then done

**Comment by SanicBTW** [comment]
![image](https://user-images.githubusercontent.com/58010536/209496147-c26a6496-bacd-4969-89ca-e9e4e4a53336.png)
ez

**Comment by LEVIXDDLMAO** [comment]
did you do on your engine?

**Comment by SanicBTW** [comment]
yea

**Comment by LEVIXDDLMAO** [comment]
![image](https://user-images.githubusercontent.com/92174516/209496174-33e823ab-c468-47a0-ad02-e54c93ab10a2.png)
but why is the green fps still at 60?

**Comment by SanicBTW** [comment]
apparently what it does is that changes the fps text to get the FlxG.updateFramerate which is 120 while FlxG.drawFramerate is still at 60

**Comment by SanicBTW** [comment]
From CoolCounter.hx:
`'FPS: ${FlxMath.bound(Math.round(times.length + cacheCount), 0, FlxG.updateFramerate)}\n';`

**Comment by LEVIXDDLMAO** [comment]
ohhhh

**Comment by SanicBTW** [comment]
While the official OpenFL FPS Counter code is this
`currentFPS = Math.round((currentCount + cacheCount) / 2);`

**Comment by LEVIXDDLMAO** [comment]
is there a way to fix that ( I dont think i have that on my engine

**Comment by SanicBTW** [comment]
just create your own counter extending the base openfl fps

**Comment by LEVIXDDLMAO** [comment]
Where should i put it? should i make a new thing in openFL /Displays/ ?

**Comment by SanicBTW** [comment]
lemme try to do one

**Comment by LEVIXDDLMAO** [comment]
kk

**Comment by SanicBTW** [comment]
![image](https://user-images.githubusercontent.com/58010536/209496824-6331254f-29e4-405f-82ca-1f83bca717b3.png)
me when

**Comment by LEVIXDDLMAO** [comment]
oooooo

**Comment by LEVIXDDLMAO** [comment]
Infinity Engine and your engine coalb when?

**Comment by SanicBTW** [comment]
theres actually no visible change, its just update not draw tho, if it was draw vsync would hit

**Comment by LEVIXDDLMAO** [comment]
> theres actually no visible change, its just update not draw tho, if it was draw vsync would hit

Still i would still like to have it

**Comment by SanicBTW** [comment]
eh fine

**Comment by LEVIXDDLMAO** [comment]
lol you dont gotta

**Comment by LEVIXDDLMAO** [comment]
when death toll port died

**Comment by MemeHoovy** [comment]
Hey Levi, I'mma add a few bots to your server, since the ones we got are just protection, so atleast we can have bots to mess around with (just to help deal with boredom)

**Comment by LEVIXDDLMAO** [comment]
> Hey Levi, I'mma add a few bots to your server, since the ones we got are just protection, so atleast we can have bots to mess around with (just to help deal with boredom)

thats fine, just dont invite scam bots

**Comment by LEVIXDDLMAO** [comment]
I found better fnf keybinds "zxl;"

**Comment by MemeHoovy** [comment]
> > Hey Levi, I'mma add a few bots to your server, since the ones we got are just protection, so atleast we can have bots to mess around with (just to help deal with boredom)
> 
> thats fine, just dont invite scam bots

I'll try not to, I'll check them on a separate server with alts

**Comment by LEVIXDDLMAO** [comment]
> > > Hey Levi, I'mma add a few bots to your server, since the ones we got are just protection, so atleast we can have bots to mess around with (just to help deal with boredom)
> > 
> > 
> > thats fine, just dont invite scam bots
> 
> I'll try not to, I'll check them on a separate server with alts to test if they're safe or not

kk

**Comment by SanicBTW** [comment]
alright levi i added the custom counter, check it cuz im going to bed soon

**Comment by LEVIXDDLMAO** [comment]
i will night!

**Comment by MemeHoovy** [comment]
goodnight sanco

**Comment by LEVIXDDLMAO** [comment]
:D

**Comment by MemeHoovy** [comment]
> :D

**Hugs you** ^w^

**Comment by LEVIXDDLMAO** [comment]
**Hugs back**

**Comment by MemeHoovy** [comment]
> **Hugs back**

:)))

**Comment by LEVIXDDLMAO** [comment]
hmm the counter didn't work

**Comment by MemeHoovy** [comment]
damn, but uh, I figured out how casts work

**Comment by LEVIXDDLMAO** [comment]
casts?

**Comment by MemeHoovy** [comment]
https://haxe.org/manual/expression-cast.html

**Comment by LEVIXDDLMAO** [comment]
ohhh

**Comment by SanicBTW** [comment]
> hmm the counter didn't work

Wdym worked perfectly fine for me

**Comment by LEVIXDDLMAO** [comment]
idk- it didn't show up

**Comment by SanicBTW** [comment]
Just set FlxG.updateFramerate = 120;

**Comment by LEVIXDDLMAO** [comment]
on what?

**Comment by MemeHoovy** [comment]
I thought you went to sleep

**Comment by LEVIXDDLMAO** [comment]
![image](https://user-images.githubusercontent.com/92174516/209499425-f0b079e0-d807-4742-b2c1-654e6979c318.png)

**Comment by MemeHoovy** [comment]
uh, use code from my engine

**Comment by LEVIXDDLMAO** [comment]
hm?

**Comment by MemeHoovy** [comment]
wait no, uh, try putting this in musicbeatstate
```
if (FlxG.stage != null)
FlxG.updateFramerate = 120;
```

**Comment by LEVIXDDLMAO** [comment]
> wait no, uh, try putting this in musicbeatstate, under create
> 
> ```
> if (FlxG.stage != null)
> FlxG.updateFramerate = 120;
> ```

can you do it on your fork?

**Comment by LEVIXDDLMAO** [comment]
I think i got it

**Comment by LEVIXDDLMAO** [comment]
didn't work lmao

**Comment by SanicBTW** [comment]
Is it that hard to open the debugger and write FlxG.updateFramerate = 120 and hit enter

**Comment by LEVIXDDLMAO** [comment]
OHHHH

**Comment by LEVIXDDLMAO** [comment]
IM DUMB

**Comment by SanicBTW** [comment]
You can also go to Main.hx and write the same thing after adding FlxGame

**Comment by LEVIXDDLMAO** [comment]
ooo

**Comment by SanicBTW** [comment]
I'm going to sleep now, gn

**Comment by LEVIXDDLMAO** [comment]
night!

**Comment by LEVIXDDLMAO** [comment]
It worked :D

**Comment by LEVIXDDLMAO** [comment]
but on 120 fps the main menu is hard to contorl

**Comment by LEVIXDDLMAO** [comment]
about 70 makes the main menu slow down

**Comment by MemeHoovy** [comment]
well, atleast you got it working

**Comment by LEVIXDDLMAO** [comment]
yup!

**Comment by MemeHoovy** [comment]
and look at that, we both got pfps of people we simp for lol

**Comment by LEVIXDDLMAO** [comment]
lol :D

**Comment by LEVIXDDLMAO** [comment]
sound doesn't work

**Comment by LEVIXDDLMAO** [comment]
![image](https://user-images.githubusercontent.com/92174516/209500723-6bc4ffd3-5888-4086-bd15-1950b3d20441.png)
hard to see but lol

**Comment by MemeHoovy** [comment]
so yeah, I guess we now know why it's capped at 60 fps lol

**Comment by LEVIXDDLMAO** [comment]
lol

**Comment by SanicBTW** [comment]
Worked perfectly fine on my engine tho

**Comment by SanicBTW** [comment]
Can't sleep 💀

**Comment by LEVIXDDLMAO** [comment]
huh?

**Comment by LEVIXDDLMAO** [comment]
> Worked perfectly fine on my engine tho

ill let you test it

**Comment by SanicBTW** [comment]
I'm on phone

**Comment by LEVIXDDLMAO** [comment]
oh

**Comment by LEVIXDDLMAO** [comment]
I got the Fps to work when loading the game but main menu is fast

**Comment by MemeHoovy** [comment]
btw, did you get your discord pfp from something sus?
![b48014803f4f68b072990c4e1e1ed940](https://user-images.githubusercontent.com/97995998/209502804-9b0a1c07-1923-402a-9399-d2ab0cee82bb.png)

**Comment by LEVIXDDLMAO** [comment]
no

**Comment by MemeHoovy** [comment]
oh

**Comment by SanicBTW** [comment]
All I know is that I think that the eh I believe menu characters on story menu have some fake frame rate or something dunno

**Comment by LEVIXDDLMAO** [comment]
im not like **cough memhoovy cough**

**Comment by SanicBTW** [comment]
Well you got 120 though

**Comment by LEVIXDDLMAO** [comment]
> All I know is that I think that the eh I believe menu characters on story menu have some fake frame rate or something dunno

lol

**Comment by LEVIXDDLMAO** [comment]
yup

**Comment by LEVIXDDLMAO** [comment]
> im not like **cough memhoovy cough**

jk btw

**Comment by LEVIXDDLMAO** [comment]
hoovy im just joking dont get mad :<

**Comment by MemeHoovy** [comment]
I'm not

**Comment by LEVIXDDLMAO** [comment]
oh-

**Comment by MemeHoovy** [comment]
> All I know is that I think that the eh I believe menu characters on story menu have some fake frame rate or something dunno

you're not wrong

**Comment by LEVIXDDLMAO** [comment]
look at my twitter some one made it

**Comment by MemeHoovy** [comment]
idk, don't see it

**Comment by LEVIXDDLMAO** [comment]
hm?

**Comment by LEVIXDDLMAO** [comment]
another fun fact about W-Side BF

**Comment by MemeHoovy** [comment]
I don't see the tweet for who made it

**Comment by MemeHoovy** [comment]
> another fun fact about W-Side BF

about that, I haven't been working on music for the mod since I didn't know what to make next

**Comment by LEVIXDDLMAO** [comment]
lol but anyways

**Comment by LEVIXDDLMAO** [comment]
https://twitter.com/DaThugWizard/status/1606769112239464448?s=20&t=sFP-CUn9kIy3I_MnAwhUqA

**Comment by MemeHoovy** [comment]
> https://twitter.com/DaThugWizard/status/1606769112239464448?s=20&t=sFP-CUn9kIy3I_MnAwhUqA

not really nsfw but uh, yeah

![MehMediocreGIF](https://user-images.githubusercontent.com/97995998/209503900-1dff06d1-7302-48d6-8c27-97f7ffadc72a.gif)

**Comment by LEVIXDDLMAO** [comment]
I love the art im friends with the person who made it ( he might work on W-Sides )

**Comment by LEVIXDDLMAO** [comment]
so be prepaired for that

**Comment by MemeHoovy** [comment]
oooh, okay

**Comment by LEVIXDDLMAO** [comment]
lol

**Comment by LEVIXDDLMAO** [comment]
Friday Night Funkin' But Levi sings it

**Comment by LEVIXDDLMAO** [comment]
> btw, did you get your discord pfp from something sus?
> 
> ![b48014803f4f68b072990c4e1e1ed940](https://user-images.githubusercontent.com/97995998/209502804-9b0a1c07-1923-402a-9399-d2ab0cee82bb.png)

I had to ask if it was okay if i used it

**Comment by MemeHoovy** [comment]
huh, didn't know that, but cool

**Comment by LEVIXDDLMAO** [comment]
lol

**Comment by LEVIXDDLMAO** [comment]
W-Side week 1?

**Comment by MemeHoovy** [comment]
wait what?

**Comment by LEVIXDDLMAO** [comment]
W-Side week 1 ? when

**Comment by MemeHoovy** [comment]
you saying you want me to do the music for week 1 right?

**Comment by LEVIXDDLMAO** [comment]
yup

**Comment by MemeHoovy** [comment]
alright, let me finish up a song I'm making for another mod, and I'll do that (unless it turns 1 or 1:30 am, since I gotta get up early)

**Comment by LEVIXDDLMAO** [comment]
kk

**Comment by MemeHoovy** [comment]
I mean, you could try learning FL to make music yourself if you want lol

**Comment by MemeHoovy** [comment]
(tho that might take a long while)

**Comment by LEVIXDDLMAO** [comment]
> I mean, you could try learning FL to make music yourself if you want lol

I dont think its on chromebook

**Comment by LEVIXDDLMAO** [comment]
well web

**Comment by MemeHoovy** [comment]
uh, I looked it up and no, but, I'm sure you can find something tho lol

**Comment by LEVIXDDLMAO** [comment]
lol

**Comment by MemeHoovy** [comment]
also BeastlyGhost accepted my buddy request on gamebanana

**Comment by LEVIXDDLMAO** [comment]
ooo

**Comment by LEVIXDDLMAO** [comment]
im working on pokehell icons

**Comment by LEVIXDDLMAO** [comment]
![image](https://user-images.githubusercontent.com/92174516/209508769-c445cfd5-5bdb-40e0-8212-c1efb8adfbaa.png)
sally icon :D

**Comment by MemeHoovy** [comment]
cool :)

**Comment by LEVIXDDLMAO** [comment]
coloring them in now

**Comment by LEVIXDDLMAO** [comment]
discord is broken again

**Comment by LEVIXDDLMAO** [comment]
@MemeHoovy

**Comment by MemeHoovy** [comment]
oh, here's what I did

![Screenshot 2022-12-26 013232](https://user-images.githubusercontent.com/97995998/209512301-d73b831f-e973-4011-82cb-204ad9a1c4ba.png)

**Comment by LEVIXDDLMAO** [comment]
lol

**Comment by MemeHoovy** [comment]
also it's over 1:30 PM, so I'm gonna sleep so we can open presets

**Comment by LEVIXDDLMAO** [comment]
that thing >:( gave me and sanco a bad ship

**Comment by LEVIXDDLMAO** [comment]
night

**Comment by MemeHoovy** [comment]
> that thing >:( gave me and sanco a bad ship

ikr lol, but also goodnight

**Comment by LEVIXDDLMAO** [comment]
lol nighttt

**Comment by MemeHoovy** [comment]
hey @LEVIXDDLMAO I gifted you nitro
