### ISSUE TITLE
feature request: a noteskin selector

### ISSUE THREAD

**Issue by fnfporterhi** [SanicBTW/FNF-PsychEngine-0.3.2h#22]
i only have circles at the moment, i will add more,

kinda got these from OS engine
![NOTE_assets](https://user-images.githubusercontent.com/99343223/211018693-77a8a3cc-4f99-435d-bda9-91e93cc0d786.png)

**Comment by fnfporterhi** [comment]
adding a google drive for the xml

**Comment by fnfporterhi** [comment]
https://drive.google.com/drive/folders/1QLXHNRgH3fcREg3VEjCwhQ8H8TqtZo8N?usp=share_link

this has all of the files for the noteskins

**Comment by MemeHoovy** [comment]
cool

**Comment by SanicBTW** [comment]
i forgot to edit the readme saying that this engine is no longer being developed and any feature request will be moved to the new engine im working on but thanks for the files!

**Comment by fnfporterhi** [comment]
yw
