### ISSUE TITLE
problem: dissaperance freezes about 1:20 left

### ISSUE THREAD

**Issue by fnfporterhi** [SanicBTW/FNF-PsychEngine-0.3.2h#23]
it freezes when those side notes come in when miku screames

**Comment by SanicBTW** [comment]
bros making issues about online songs 💀 jokes aside im not working on this repo anymore, should archive it soon

**Comment by fnfporterhi** [comment]
ok sorry sorry

**Comment by SanicBTW** [comment]
dw lol

**Comment by fnfporterhi** [comment]
i should prob close this

**Comment by SanicBTW** [comment]
i will check on it soon, prob some song events shit dunno

**Comment by fnfporterhi** [comment]
you’re fine

**Comment by SanicBTW** [comment]
oki
