### ISSUE TITLE
another issue cause ded song list

### ISSUE THREAD

**Issue by fnfporterhi** [SanicBTW/FNF-PsychEngine-0.3.2h#24]
![Screenshot 2023-03-07 8 53 23 AM](https://user-images.githubusercontent.com/99343223/223442584-affb4383-1cdb-4664-a1aa-963488817b9a.png)

**Comment by SanicBTW** [comment]
My bad I should've added an indicator when the server is down or something

**Comment by fnfporterhi** [comment]
alright

**Comment by SanicBTW** [comment]
The host is officially dead

**Comment by fnfporterhi** [comment]
wait what?

**Comment by fnfporterhi** [comment]
so no more online songs list? or are you making another host? i’m confused.

**Comment by SanicBTW** [comment]
prob no more online songs list until i find a secure host, i cant use sancopublic.ddns.net because is an insecure context and cant do much about ssl on that, im trying to find a host for now

**Comment by fnfporterhi** [comment]
you need a dns right

**Comment by SanicBTW** [comment]
i only need a domain

**Comment by fnfporterhi** [comment]
hmmmmm

**Comment by fnfporterhi** [comment]
lemme do my searching.

**Comment by SanicBTW** [comment]
i got one but it wont let me change nameservers to bind cloudflare

**Comment by fnfporterhi** [comment]
what’s cloudflare

**Comment by SanicBTW** [comment]
what 💀

**Comment by fnfporterhi** [comment]
> it wont let me change nameservers to bind cloudflare
.

**Comment by fnfporterhi** [comment]
also don’t judge cause i’m new to coding and sruff

**Comment by fnfporterhi** [comment]
stuff*

**Comment by SanicBTW** [comment]
ok ok its just that everything uses cloudflare and i thought you would know that

**Comment by fnfporterhi** [comment]
oh okay

**Comment by fnfporterhi** [comment]
i recorded me playing a song on fnf in slow
motion, where i spammed it was 1         2.                 3.                  4.               *repeat*

**Comment by fnfporterhi** [comment]
oml

**Comment by fnfporterhi** [comment]
it never adds so many spaces

**Comment by fnfporterhi** [comment]
never found a server. guess this means no more song list. rip, you served us well 🫡

**Comment by fnfporterhi** [comment]
WAIT

**Comment by fnfporterhi** [comment]
use nextDNS

**Comment by SanicBTW** [comment]
i need a domain, i dont want to change my router dns settings 💀

**Comment by SanicBTW** [comment]
i mean i only have 1€ lol

**Comment by fnfporterhi** [comment]
maybe found one

**Comment by fnfporterhi** [comment]
never mind

**Comment by fnfporterhi** [comment]
https://www.cloudns.net/

**Comment by fnfporterhi** [comment]
shit

**Comment by SanicBTW** [comment]
OK GOOD NEWS

**Comment by SanicBTW** [comment]
I GOT A NEW HOST AND ITS .com LETS GOOOOO

**Comment by SanicBTW** [comment]
alright online services fixed

**Comment by fnfporterhi** [comment]
LETS GOOOOOOOOOOOO (sorry i just woke up)

**Comment by fnfporterhi** [comment]
servers ded

**Comment by SanicBTW** [comment]
Did you even read my profile 💀

**Comment by fnfporterhi** [comment]
uhhhh whats on the profile

**Comment by SanicBTW** [comment]
![Screenshot_20230404-184802_GitHub.png](https://user-images.githubusercontent.com/58010536/229861368-8a936c43-add9-45d4-b9b6-fb4d031fbf73.png)

💀?

**Comment by fnfporterhi** [comment]
oh shit what happened?

**Comment by fnfporterhi** [comment]
why did it die

**Comment by SanicBTW** [comment]
Stuff lol

**Comment by fnfporterhi** [comment]
would you mind helping me with a port? it's not mine, but i cant figure out whats wrong with it
https://pix3lslay3r101.github.io/VsDaveBrowser/Vanilla/
tutorial is splitathon, and it wont load
